name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # checkout resource
      - name: CheckOut
        uses: actions/checkout@v3
        
      # generate artifacts
      - name: instal and build
        run: |
             npm i pnpm -g
             pnpm install
             pnpm docs:build

      - name: github-ci
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: .vitepress/dist
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
